### ISSUE TITLE
아침과 저녁을 비활성화 하는 기능을 만들어 주세요

### ISSUE THREAD

**Issue by Inlayo** [todaywhat/TodayWhat-iOS#141]
### Describe

아침 저녁이 없는 학교에 다니면 전날 저녁이나 아침에 급식을 확인하면 [아침] 또는 [저녁] 이렇게 나오는데 점심만 나올수 있도록 아침과 저녁을 끄는 기능을 만들어 주세요

**Comment by baekteun** [comment]
> 아침 저녁이 없는 학교에 다니면 전날 저녁이나 아침에 급식을 확인하면 [아침] 또는 [저녁] 이렇게 나오는데 점심만 나올수 있도록 아침과 저녁을 끄는 기능을 만들어 주세요
> 

@Inlayo 안녕하세요, 문의주셔서 감사합니다. 위젯을 길게 누르면 나오는 '위젯 편집'에서 시간을 고정하는 기능을 제공합니다 :) 감사합니다!

**Comment by Inlayo** [comment]
아하 기능을 모르고 있었네요ㅠㅠ
